server:
  port: 8003


eureka:
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.cloud.client.ip-address}:${server.port}


spring:
  datasource:
    driverClassName: ${rccp.micro.datasource.driverClassName}
    druid:
      main-db:
        url: ${rccp.micro.datasource.url}
        username: ${rccp.micro.datasource.username}
        password: ${rccp.micro.datasource.password}
      user-db:
        url: ${rccp.micro.datasource.user_url}
        username: ${rccp.micro.datasource.username}
        password: ${rccp.micro.datasource.password}
      search-db:
        url: ${rccp.micro.datasource.search_url}
        username: ${rccp.micro.datasource.username}
        password: ${rccp.micro.datasource.password}
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://${eureka.instance.hostname}:8767/

  cloud:
    instance-count: 1
    instance-index: 0
    stream:
      kafka:
        binder:
          brokers: ${rccp.micro.stream.kafka.binder.brokers}
          zk-nodes: ${rccp.micro.stream.kafka.binder.zk-nodes}
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1

ribbon:
  eureka:
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

debug: true
logging:
  level:
    com.zhuj.micro.service.**.*: debug

#视频用户背景图
videoBackGroundImage: https://rccp-dfs.oss-cn-beijing.aliyuncs.com/industry/pic/20200616182541762124673.jpg
#七牛云相关
qnaccessKey: IgFqVYv0l245Skw1KPBje1PoAYaNUCoaXK4uM3ma
qnsecretKey: v5WQEaoHlTknZ8Z3K1saclHzETbX2ougyYGPRA_A
qnhubName: zhujianyun
RTMPpubUrl: pili-publish.zhujianyun.com
RTMPliveUrl: pili-live-rtmp.zhujianyun.com
HLSliveUrl: pili-live-hls.zhujianyun.com
HDLliveUrl: pili-live-hdl.zhujianyun.com
liveImageUrl: pili-snapshot.zhujianyun.com
#环信相关
GRANT_TYPE: client_credentials
HXCLIENT_ID: YXA6iBUfgfy0ROKS_S1qRz3ckQ
HXCLIENT_SECRET: YXA6Yx55hK-C3VMD80sxPLG05fh-K1E
HXAPP_NAME: demo
HXORG_NAME: 1137201013239659

#获取天气
weatherUrl: http://www.tianqiapi.com/api/
#当前服务器ip
weatherServerIp: http://123.57.85.64
#天气图片路径
weatherImgUrl: /weatherImg/cucumber/
weatherAppid: 19383894
weatherAppSecret: vG9LX2vn
weatherVersion: v61

#-------------阿里云配置公共参数---------
#阿里云 accessKeyId
accessKeyId: LTAICZtWTxGneJgX
#阿里云 accessKeySecret
accessKeySecret: ahJozKLHA64fFQoThCJZUnIE9PFPuJ
#-------------阿里云配置公共参数---------


#环境配置
endpoint: oss-cn-beijing.aliyuncs.com
endpoint2: https://oss-cn-beijing.aliyuncs.com
bucketName: rccp-dfs
accessUrl: https://rccp-dfs.oss-cn-beijing.aliyuncs.com
fileUrl: http://192.168.1.89:8081
fastDfsUrl: http://192.168.1.89:8888
fastdfs:
  trackerServer: 192.168.1.89:22122
  connectTimeout: 5000
  networkTimeout: 30000
  trackerHttpPort: 8888