rccp:
  micro:
    serverIp: www.rccp.com
    eurekaUserName: admin
    eurekaPassword: admin
    # 数据库配置
    datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.1.108:3306/rccp_v2?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=GMT%2b8
      user_url: jdbc:mysql://192.168.1.108:3306/rccp_user?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=GMT%2b8
      search_url: jdbc:mysql://192.168.1.108:3306/rccp_v2?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=GMT%2b8
      username: root
      password: zhongzhu11@#$
      type: com.alibaba.druid.pool.DruidDataSource

    #Redis服务器配置
    redis:
      host: 192.168.1.108
      port: 6379
      password: zhongzhu11@#$
      timeout: 10000

    #kafka配置
    stream:
      kafka:
#        binder:
#          brokers: 192.168.1.108:9092
#          zk-nodes: 192.168.1.108:2181
        binder:
          minPartitionCount: 3  # 分区数量，主要就是为了减轻单台服务器的压力，扩大并发量
          brokers: 192.168.1.85:9092,192.168.1.89:9092,192.168.1.80:9092 # kafka服务地址和端口
          autoCreateTopics: true
          autoAddPartitions: true

    #上传文件大小配置  -1 为不限制大小
    servlet:
      multipart:
        max-file-size: -1
        max-request-size: -1

    #分布式事务管理器地址
    tx-lcn:
      client:
        manager-address: 192.168.1.108:19990
    #redis缓存使用的数据库索引
    rediscache:
      database: 2


spring:
  profiles:
    active: dev

#只有非正式环境会用到
serverIp: ${rccp.micro.serverIp}

#通过密码模式获取token地址
#TOKEN_PWD_URL: http://192.168.1.71:8764/oauth/token?grant_type=password
TOKEN_PWD_URL: http://192.168.1.70:8081/api-oauth/oauth/token?grant_type=password
secret: 123456

#请求处理的超时时间
ribbon.ReadTimeout: 120000
#请求连接的超时时间
ribbon.ConnectTimeout: 30000