server:
  port: 8768

eureka:
  instance:
     prefer-ip-address: true
     instance-id: ${spring.cloud.client.ip_address}:${server.port}

spring:
  security:
    user:
      name: "admin"
      password: "admin"

