server:
  port: 8801
  tomcat:
    max-http-post-size: 0
    max-http-header-size: 10485760

eureka:
  instance:
    hostname: www.rccp.com
    prefer-ip-address: true
    instance-id:  ${spring.cloud.client.ip-address}:${server.port}


spring:
  datasource:
    driverClassName: ${rccp.micro.datasource.driverClassName}
    url: ${rccp.micro.datasource.url}
    username: ${rccp.micro.datasource.username}
    password: ${rccp.micro.datasource.password}
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://${eureka.instance.hostname}:8767/

  cloud:
    instance-count: 1
    instance-index: 0
    stream:
      kafka:
        binder:
          brokers: ${rccp.micro.stream.kafka.binder.brokers}
          zk-nodes: ${rccp.micro.stream.kafka.binder.zk-nodes}
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

thymeleaf:
       mode: HTML5


#-------------阿里云配置公共参数---------
#阿里云 accessKeyId
accessKeyId: LTAICZtWTxGneJgX
#阿里云 accessKeySecret
accessKeySecret: ahJozKLHA64fFQoThCJZUnIE9PFPuJ
#图片
picKey: pic
#视频
videoKey: video
#文件
fileDocKey: fileDoc
#-------------阿里云配置公共参数---------


#环境配置
endpoint: oss-cn-beijing.aliyuncs.com
bucketName: rccp-dfs
accessUrl: https://rccp-dfs.oss-cn-beijing.aliyuncs.com

#阿里云转码配置


#线上配置
pipelineId: 261882f700fa4991aba01a6c35f0e1f0 #管道ID
location: oss-cn-beijing #输入OSS Bucket所在数据中心（OSS Location）
regionId: cn-beijing # #地域ID
templateId: 1db19c1364614bd19c94cc542c3174f5   #转码模板ID









