server:
  port: 8805


eureka:
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.cloud.client.ip-address}:${server.port}


spring:
  datasource:
    driverClassName: ${rccp.micro.datasource.driverClassName}
    url: ${rccp.micro.datasource.url}
    username: ${rccp.micro.datasource.username}
    password: ${rccp.micro.datasource.password}
    type: ${rccp.micro.datasource.type}
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://${eureka.instance.hostname}:8767/

  cloud:
    instance-count: 1
    instance-index: 0
    stream:
      kafka:
        binder:
          brokers: ${rccp.micro.stream.kafka.binder.brokers}
          zk-nodes: ${rccp.micro.stream.kafka.binder.zk-nodes}
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1


management:
  endpoints:
    web:
      exposure:
        include: "*"


ribbon:
  eureka:
    enabled: true


mybatis:
  mapper-locations: classpath:mapper/**/*.xml

debug: true
logging:
  level:
    com.zhuj.micro.service.**.*: debug

#电商ID
EBUSINESSID: 1676265
#电商加密私钥，快递鸟提供，注意保管，不要泄漏
APIkey: 4d4f1e9c-9c2b-45e7-914c-812765c2f10c
#快递鸟 请求url 物流即时查询
ReqURL: http://api.kdniao.com/Ebusiness/EbusinessOrderHandle.aspx
