server:
  port: 8804
  tomcat:
    max-http-post-size: 0
    max-http-header-size: 104857600
    uri-encoding: UTF-8


eureka:
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.cloud.client.ip-address}:${server.port}



spring:
  datasource:
    driverClassName: ${rccp.micro.datasource.driverClassName}
    druid:
      main-db:
        url: ${rccp.micro.datasource.url}
        username: ${rccp.micro.datasource.username}
        password: ${rccp.micro.datasource.password}
      user-db:
        url: ${rccp.micro.datasource.user_url}
        username: ${rccp.micro.datasource.username}
        password: ${rccp.micro.datasource.password}
      search-db:
        url: ${rccp.micro.datasource.search_url}
        username: ${rccp.micro.datasource.username}
        password: ${rccp.micro.datasource.password}
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://${eureka.instance.hostname}:8767/

  cloud:
    instance-count: 1
    instance-index: 0
    stream:
      kafka:
        binder:
          brokers: ${rccp.micro.stream.kafka.binder.brokers}
          zk-nodes: ${rccp.micro.stream.kafka.binder.zk-nodes}
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
ribbon:
  eureka:
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

debug: true
logging:
  level:
    com.zhuj.micro.user.service.**.*: debug



#通过密码模式获取token地址
#TOKEN_PWD_URL: http://172.17.186.112:8764/oauth/token?grant_type=password
TOKEN_PWD_URL: http://172.17.186.112:8763/api-oauth/oauth/token?grant_type=password



#微信支付参数
WXAPP_ID:
APP_SECRET:
WXMCH_ID:
WXAPI_KEY:
NOTIFY_URL: http://172.17.186.112:8804/wxRenotify
UFDODER_URL: https://api.mch.weixin.qq.com/pay/unifiedorder
CHECK_URL: https://api.mch.weixin.qq.com/pay/orderquery
TRADE_TYPE: NATIVE
SIGN_TYP: HMAC-SHA256


#支付宝支付参数pc  2021001163629730
ALAPP_ID: 2021001189642509
ALAPP_PRIVATE_ID: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCzaj1Obfspo4eNJA8+KU4uy9qAlAfPm1ikslOiWB4meUn21RPkPtvubQDvGNySufxpfoQFA/Xt6Y8YvsRQydwWQvej3J8DlnvCYVQthyzw1c8RcbWzRvLBMp/gZk34rAuEPrrPl/KZyCrXHKmyZbxyZH3c2yrCBD2bgsMoViu9HOZQ5hHhViSCpuNmHKjnCuZyF30AkbR4Qsv0ZXgmeeVZIsjXV/NEhSPlHXSdyXprjcgn6fM6qYDPTyL5wNvb1RUx/uFndmQIxdA3qSZ/IMJ9wpsBPvbBDCYFKPbaFIRehhs1gojnbBu80QAP1Syrn1M5lGmqhsKXZkJ3CXzVVUZJAgMBAAECggEBAKAalzjM9kvzDTyLSDrte0JRUdxZvRqrgw/9vpppzgYBSFrHTKfq3DJI/YNgCT26UKAHcWJUZXr4aGTpn6CEci0/d2O3tgLqn+gXGJpEPXtxIQZtFXs1Pd3gAkGqqbvWM7TAkc48xxYqROiPQHPdS6w9NwAGaIKYbC3BI8x0ETYA+a3HXE6Zt5Sa3+zt3rWSUBOEoUyc784N98MZY8o1VbFyZs9EkDICUhX/t3zX6fhyzMp7vK/rGbf5q3AdWAn3kxbi5/StVrlwjz7IavbLT/cz/mTL98zVUbOpbNYulQZuNP+6C19uaDie/dIc+cA2wsEWjUTuFOkeG1SSDPeCRA0CgYEA8oRSEF6wNAL90/WVizZQT24sR039FnAEQ1u15Br0fezwPVjZh1b9CkZ3EMVguECjSokcrqq19PP05uQ1UpS5LvPwPgjKVmXxmtNI+AzOjcPDKfmECFymbFZM9t139qFC6csMNyy8OhnCpuNQgeQHM5MGVYvABd07b2dtgvPGixsCgYEAvWPOa89SU7tIOzEi1AxlCC3WZXQLeTFKpX/tTJ4I1qSgFRRqhkkja7ucfr773loMPSvnMI8zCo3jrVBTL6ICscTrLrGRoT/r89/8CamwWteY+n9CuhIZNQKkIBnEZTNhLijPhk7KesltSDuuppk1rogzgEg9x5mDIqWVhGUrhmsCgYEApdFHcx3rCIULHMQMDfWDD+xaph5y78aDg7LPOToc9YTt9mQrx9f4h/AKNRNfwFuhyrLZQ6xBYUz0pHJg6yf5PltYZnIINu7ZNW1FtSS8jj3N0YNjfXwr5mNTmG9xONamM8i7f3Y89NTsPMOsJkPNkLv0VsWI8/mCS/fB7wnTNQUCgYEAluuu9girYWAv6kN4rqQF6uOkIwq7jeMyyfnMny6ceneLveCcFtC3skU6K2KEEaeOczzGKdMjaHizg0wsThv7q6/xfi8wjuACZkAKd6TKjUmbdZruEJsVjUHCinYeJEsyWPdakHu/LOPQ+yvcPJSAy8lryQFIggOaFYUARhXc/msCgYAPhJ6OxLWs4p7QtMaHC5e6kj1FjKW5rcoxVfhd8o2b+1kbqzfxDb0GN0FVIB6hNR6ul/Zgb+B+X37imW9Dmr1WChlK5/YO2yq31v9WIR1OlkizE2RaUvoVXKMLGQBRmKHjp3NtnApmAiQpnCqPMCR/GAPrOT+oyUslklnUG54rHg==
AL_PUBLIC_ID: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn8eieG/U7Uub1TZZtK8kRNG/2NXi0tvZ8GgPx6A+WswBYziqZEzT/f3M80obztTTyc/AYLMHU6QNMbkEHUzC7j1M2DNy4pbUaK3thMGKZSFJovjeSIMB7dYGZc4Zqx7XMVvJIl7P7eOy1ZGSxOW6ACxkXiXgT7m0RYivAnE8CT4bXH+uvlbHH7XsYRh0wr8i3ggf8kjjt1L9BHiZmY9Vbwpppi6TPxUiDxeeDNdC1jVvsuLIFjyEn5NKLLmKp4biT5nTlEVqC1KQ5LKRRhP6oZ0+v7HPgra2yR+wZtwpJclgZyWlnMYzCKB3asZBiGgy13ijG6Mvc0k9SMQmGlq+MQIDAQAB
#ALNOTIFY_URL: http://172.17.186.112:8804/alRenotify/NotifyURL pc http://182.92.212.127:8763/api-user/alRenotify/NotifyURL
#ALRETURN_URL: http://172.17.186.112:8804/alRenotify/ReturnURL pc http://182.92.212.127:8763/api-user/alRenotify/ReturnURL
ALNOTIFY_URL: https://m.zhujianyun.com/api-user/alRenotify/NotifyURL
ALRETURN_URL: https://m.zhujianyun.com/api-user/alRenotify/ReturnURL
ALSIGN_TYPE: RSA2
ALCHARSET: utf-8
ALGETEWAY_URL: https://openapi.alipay.com/gateway.do
AL_CALL_BACK: http://182.92.212.127/zhujianyun/#/PersonMeg

DEFAULT: 0
ONE: 1
TWO: 2
THREE: 3
FOUR: 4
FIVE: 5

DEFAULT_MONEY: 0
ONELEVEL: 10
TWOLEVEl: 100
THREELEVEL: 500
FOURLEVEL: 2000

